version: '3.2'
services:
  jenkins:
    build:
      context: jenkins/
    privileged: true
    user: root
    container_name: jenkins
    volumes:
      - /tmp/jenkins:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
      - /var/run/docker.sock:/var/run/docker.sock
